### ISSUE TITLE
Touchscreen doesn't work at all on windows 11 build 22621

### ISSUE THREAD

**Issue by hiprivsid** [qaz6750/XiaoMi9-Drivers#11]
On 1st boot touchscreen work, after reboot it doesn't.
I tried reinstall driver, but it didn't give anything

**Comment by qaz6750** [comment]
* I'm sorry for the bad experience you had. The improvement and enhancement work for touch has already begun

**Comment by qaz6750** [comment]
* The problem has been alleviated (expected), therefore it is closed.
