### ISSUE TITLE
适配一下redmi K20 pro

### ISSUE THREAD

**Issue by GanaiYing1314** [qaz6750/Xiaomi9-Drivers#6]
redmi K20 pro基本和米9驱动通用，只需修改一下驱动名

**Comment by qaz6750** [comment]
* 很抱歉，该储存库仅支持Cepheus（mi9）,并且K20p事实上已经被支持
* **该储存库只会为Mi9提供支持，对于其他设备，我不会承诺任何东西，**如果你执意要使用，那我只能祝你幸运
