### ISSUE TITLE
米9 安裝問題

### ISSUE THREAD

**Issue by gary4635941** [qaz6750/Xiaomi9-Drivers#7]
大佬您好

上周有收到您的回信，謝謝您的回覆
我使用的ROM是這個版本(V12.5.1.0.RFAMIXM、MIUI:12、Android 11.0)(如下圖)
![321](https://github.com/qaz6750/Xiaomi9-Drivers/assets/64147935/3c2868d6-3509-46e2-8afc-a531bbe78c8e)
使用的工具箱:Mindows工具箱下载器2023-8-18-1
使用的安裝檔:【努比亚Z18、红魔Mars推荐】22000.1.210604-1628.CO_RELEASE_CLIENTPRO_OEMRET_A64FRE_ZH-CN.wim
安裝完會是這樣:https://drive.google.com/file/d/1-v7lZBOUEy0HWs9jFoDQNqlFtOTEd2Sw/view?usp=sharing
但如果把驅動全部刪除的話會是這樣:https://drive.google.com/file/d/100Nkfggyo23-PVlTMux891jP8XcXn_lT/view?usp=sharing
有看過您的回信，那代表我無法正常的安裝驅動(目前不知道怎麼解決 不知道跟陸版ROM有沒有影響、跟WIN11安裝包有沒有影響
以及USB指令是讓我比較頭痛的部分，已經透過供電HUB(JCD371)接滑鼠及鍵盤到手機上，但滑鼠、鍵盤還是不動作，導致有接跟沒接一樣(我想就像您說的，因為我把驅動刪除導致USB不正常
但如果不刪驅動會卡K logo，如果刪驅動，則USB不動作 所以想不到如何正常安裝驅動了

**Comment by qaz6750** [comment]
* 目前该问题在我的设备上无法复现
* 目前，Mi9最新MIUI版本为12.5.6.0
